version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    networks:
      - network

  app:
    image: your-docker-image-name
    container_name: spring-boot-app
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/products
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123
    ports:
      - "8088:8088"
    depends_on:
      - postgres
    networks:
      - network

networks:
  network:
    driver: bridge